### ISSUE TITLE
Hw to install xar utility on Linux/Ubuntu or Windows?

### ISSUE THREAD

**Issue by AliceNZ** [korylprince/go-macos-pkg#1]
Hi, I tried
1) sudo apt-get install xar
E: Unable to locate package xar

2) try build and install from the code
 https://code.google.com/archive/p/xar/downloads 
and it came out this error when running $./configure

checking for OpenSSL_add_all_ciphers in -lcrypto... no
configure: error: Cannot build without libcrypto (OpenSSL)

The issue is that the xar code I was trying to build is 10 years old, and uses the deprecated OpenSSL 1.0 API. 

https://github.com/mackyle/xar/tree/master/xar looks even older

So how to install xar utility on Linux?

**Comment by korylprince** [comment]
You can take a look at [this Dockerfile](https://github.com/korylprince/ls-relay-cert/blob/master/Dockerfile#L8-L22) that builds xar from source for some guidance. Hopefully one day we'll have a pure Go xar implementation, but until then, this should work.
